### PR TITLE
do not pass hangman.secretWord to HangmanCanvas

### PR DESCRIPTION
**Pull request by abernier**
this is not really useful since already in `hangman.secretWord` + better to have a single source of truth

### CODE REVIEW

**Comment by abernier** [comment]
since `hangman` instance is global https://github.com/ironhack-labs/lab-canvas-hangman/blob/master/javascript/hangman.js#L36 we can access `hangman.secretWord` from `HangmanCanvas` methods

**Review by ross-u — CHANGES_REQUESTED** [review]
The mention of **secretWord** in the Iteration 2 is removed but it still remains in Iteration 1.  This will probably cause confusion for the students.

**Review by ross-u — CHANGES_REQUESTED** [review]
In addition to removing the **secretWord** we should give a hint to the student how to handle the chosen secret word. The PR should be updated to provide that example or guidance in the README and also in the starter code

**Comment by ross-u** [comment]
@abernier Thanks for bringing this up. I went over the commits and left couple of comments. To summarize, I believe that before merging the PR and removing the property **secretWord** it should be updated to include the following:
- Update README in all iterations and remove all mentions of secretWord
- Update the README and the starter code example to provide guidance for the student on how to store the secret word when the game starts.

**Comment by abernier** [comment]
> The mention of **secretWord** in the Iteration 2 is removed but it still remains in Iteration 1. This will probably cause confusion for the students.

[Iteration 1](https://github.com/ironhack-labs/lab-canvas-hangman/blob/0a7407f300ef751e10ad7fec2183797a0a619334/README.md#L50) is ok about `secretWord`, it actually just asks the student to uncomment that line: https://github.com/ironhack-labs/lab-canvas-hangman/blob/0a7407f300ef751e10ad7fec2183797a0a619334/javascript/hangman.js#L45

`hangman.secretWord` now exists and we can access it directly from the `HangmanCanvas` class

**Pull request closed without merging**
